import type { GlobalPurchaseRow } from "@/types/global-purchases"

export const globalPurchasesRows: GlobalPurchaseRow[] = [
  {
    id: "gp-1",
    title: "Бетон М300",
    unit: "м³",
    planQuantity: 120,
    planPrice: 6200,
    factQuantity: 115,
    factPrice: 6400,
  },
  {
    id: "gp-2",
    title: "Арматура А500С 12мм",
    unit: "т",
    planQuantity: 18.5,
    planPrice: 52000,
    factQuantity: 19.2,
    factPrice: 51500,
  },
  {
    id: "gp-3",
    title: "Кирпич керамический",
    unit: "тыс. шт",
    planQuantity: 45,
    planPrice: 15000,
    factQuantity: 44,
    factPrice: 15200,
  },
  {
    id: "gp-4",
    title: "Кабель ВВГнг-LS 3×2.5",
    unit: "м",
    planQuantity: 2800,
    planPrice: 85,
    factQuantity: 2750,
    factPrice: 88,
  },
  {
    id: "gp-5",
    title: "Труба стальная Ø50",
    unit: "м",
    planQuantity: 340,
    planPrice: 420,
    factQuantity: 355,
    factPrice: 410,
  },
  {
    id: "gp-6",
    title: "Краска фасадная",
    unit: "л",
    planQuantity: 520,
    planPrice: 380,
    factQuantity: 500,
    factPrice: 395,
  },
  {
    id: "gp-7",
    title: "Утеплитель минеральная вата",
    unit: "м³",
    planQuantity: 32,
    planPrice: 4800,
    factQuantity: 30,
    factPrice: 4900,
  },
  {
    id: "gp-8",
    title: "Окна ПВХ 1200×1500",
    unit: "шт",
    planQuantity: 28,
    planPrice: 12500,
    factQuantity: 28,
    factPrice: 12800,
  },
  {
    id: "gp-9",
    title: "Двери входные металлические",
    unit: "шт",
    planQuantity: 12,
    planPrice: 35000,
    factQuantity: 12,
    factPrice: 34200,
  },
  {
    id: "gp-10",
    title: "Сантехника (раковина + смеситель)",
    unit: "компл",
    planQuantity: 18,
    planPrice: 8900,
    factQuantity: 20,
    factPrice: 8700,
  },
]
