import type { PurchaseRow } from "@/types/purchase"

export const purchaseRows: PurchaseRow[] = [
  {
    id: "purchase-1",
    title:
      "Автоматический выключатель EKF PROxima BA-45-2000 3P 1000A 80 кА 690 В",
    planQuantity: 0,
    planPrice: 0,
    factQuantity: 1,
    factPrice: 355784,
  },
  {
    id: "purchase-2",
    title: "Кабель ВВГнг-LS 5x10",
    planQuantity: 120,
    planPrice: 680,
    factQuantity: 118,
    factPrice: 720,
  },
  {
    id: "purchase-3",
    title: "Лоток металлический перфорированный 100x50",
    planQuantity: 34,
    planPrice: 1250,
    factQuantity: 36,
    factPrice: 1190,
  },
  {
    id: "purchase-4",
    title: "Розетка силовая промышленная 32А",
    planQuantity: 18,
    planPrice: 2400,
    factQuantity: 18,
    factPrice: 2630,
  },
  {
    id: "purchase-5",
    title: "Щит распределительный навесной IP54",
    planQuantity: 4,
    planPrice: 18500,
    factQuantity: 5,
    factPrice: 17900,
  },
  {
    id: "purchase-6",
    title: "DIN-рейка оцинкованная 35 мм",
    planQuantity: 45,
    planPrice: 180,
    factQuantity: 45,
    factPrice: 176,
  },
  {
    id: "purchase-7",
    title: "Автоматический выключатель 1P 16А",
    planQuantity: 96,
    planPrice: 420,
    factQuantity: 100,
    factPrice: 415,
  },
  {
    id: "purchase-8",
    title: "Клемма проходная винтовая 4 мм2",
    planQuantity: 320,
    planPrice: 48,
    factQuantity: 300,
    factPrice: 52,
  },
  {
    id: "purchase-9",
    title: "Труба гофрированная ПВХ 25 мм",
    planQuantity: 250,
    planPrice: 38,
    factQuantity: 260,
    factPrice: 41,
  },
  {
    id: "purchase-10",
    title: "Маркировочная бирка кабельная",
    planQuantity: 1000,
    planPrice: 6,
    factQuantity: 1200,
    factPrice: 5,
  },
]
