import type { DirectoryMaterialRow } from "@/types/directory-material"

export const directoryMaterialRows: DirectoryMaterialRow[] = [
  {
    id: "mat-1",
    title: "Гипсокартон влагостойкий 12,5 мм",
    unit: "лист",
    price: 620,
    imageUrl: "",
    category: "Стеновые материалы",
  },
  {
    id: "mat-2",
    title: "Профиль стоечный 50×50",
    unit: "шт",
    price: 245,
    imageUrl: "",
    category: "Стеновые материалы",
  },
  {
    id: "mat-3",
    title: "Саморезы по металлу 25 мм",
    unit: "упак",
    price: 390,
    imageUrl: "",
    category: "Крепёж",
  },
  {
    id: "mat-4",
    title: "Шпаклевка финишная",
    unit: "меш",
    price: 780,
    imageUrl: "",
    category: "Отделочные",
  },
  {
    id: "mat-5",
    title: "Грунтовка глубокого проникновения",
    unit: "кан",
    price: 1150,
    imageUrl: "",
    category: "Отделочные",
  },
  {
    id: "mat-6",
    title: "Кабель ВВГнг-LS 3×2.5",
    unit: "м",
    price: 85,
    imageUrl: "",
    category: "Электрика",
  },
  {
    id: "mat-7",
    title: "Труба гофрированная ПВХ 25 мм",
    unit: "м",
    price: 38,
    imageUrl: "",
    category: "Электрика",
  },
  {
    id: "mat-8",
    title: "Краска фасадная",
    unit: "л",
    price: 380,
    imageUrl: "",
    category: "Отделочные",
  },
  {
    id: "mat-9",
    title: "Утеплитель минеральная вата",
    unit: "м³",
    price: 4800,
    imageUrl: "",
    category: "Изоляция",
  },
  {
    id: "mat-10",
    title: "Кирпич керамический",
    unit: "тыс. шт",
    price: 15000,
    imageUrl: "",
    category: "Стеновые материалы",
  },
]
