import type { ExecutionRow } from "@/types/execution"

export const executionRows: ExecutionRow[] = [
  {
    id: "exec-1",
    title: "Монтаж перегородки из ГКЛ",
    unit: "м²",
    planQuantity: 245,
    planPrice: 850,
    factQuantity: 230,
    factPrice: 920,
  },
  {
    id: "exec-2",
    title: "Шпаклевка стен",
    unit: "м²",
    planQuantity: 1200,
    planPrice: 320,
    factQuantity: 1180,
    factPrice: 340,
  },
  {
    id: "exec-3",
    title: "Электромонтаж",
    unit: "точка",
    planQuantity: 64,
    planPrice: 1800,
    factQuantity: 68,
    factPrice: 1750,
  },
  {
    id: "exec-4",
    title: "Укладка плитки",
    unit: "м²",
    planQuantity: 180,
    planPrice: 1200,
    factQuantity: 175,
    factPrice: 1280,
  },
  {
    id: "exec-5",
    title: "Малярные работы",
    unit: "м²",
    planQuantity: 950,
    planPrice: 280,
    factQuantity: 960,
    factPrice: 265,
  },
  {
    id: "exec-6",
    title: "Прокладка кабеля",
    unit: "м",
    planQuantity: 420,
    planPrice: 150,
    factQuantity: 435,
    factPrice: 148,
  },
  {
    id: "exec-7",
    title: "Монтаж подвесного потолка",
    unit: "м²",
    planQuantity: 320,
    planPrice: 950,
    factQuantity: 310,
    factPrice: 1000,
  },
  {
    id: "exec-8",
    title: "Установка дверей",
    unit: "шт",
    planQuantity: 24,
    planPrice: 4500,
    factQuantity: 24,
    factPrice: 4700,
  },
  {
    id: "exec-9",
    title: "Монтаж вентиляции",
    unit: "м²",
    planQuantity: 85,
    planPrice: 2100,
    factQuantity: 90,
    factPrice: 2050,
  },
  {
    id: "exec-10",
    title: "Сантехнические работы",
    unit: "точка",
    planQuantity: 48,
    planPrice: 2800,
    factQuantity: 52,
    factPrice: 2750,
  },
]
